---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    allow:
    # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    schedule:
      interval: daily
    assignees:
      - "root-lib"
    reviewers:
      - "root-lib"
    target-branch: "dev"
    labels:
      - "security checks"

