name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  static-query:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: helaili/github-graphql-action@2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: samples/oss-vuln.yaml
        outputFile: vulnResult.json
    - name: Upload vuln-results
      uses: actions/upload-artifact@v2
      with:
        name: vulnResult
        path: vulnResult.json
  printresults:
    name: download results
    needs: static-query
    runs-on: windows-latest
    steps:
      - name: Download vulnresults
        uses: actions/download-artifact@v2
        with:
          name: vulnResult
      - shell: bash
        run: |
          value=`cat vulnResult.json`
          echo $value
