name: dependbot_tickets

on:
  push:
    branches: [ dev ]

jobs:
  static-query:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Analyse results
      id: analyse_vuln
      uses: razorpay/security-action@githubAction-script-dependabot
      with:
        path: 'vulnResult.json'
        jira_url: ${{secrets.JIRAURL}}
        token: ${{ secrets.JIRA_SECRET}}
        github_token: ${{ secrets.PAT }}
        github_url: ${{secrets.GITURL}}
    - name: Print results json
      run: |
        echo "${{steps.analyse_vuln.outputs.ticketLists}}"
